### PR TITLE
Improve tracing

### PR DESCRIPTION
**Pull request by cephee**
Hey! 

Just a little improve & fix on the tracing call :)

Bye bye and thanks for reading :+1:

### CODE REVIEW

**Comment by cephee** [comment]
UP :)

**Comment by QuentinBontemps** [comment]
Sorry for the delay ;) 
I've merged & published new release

**Comment by cephee** [comment]
Great, tks !  
Also If you have a little time, it would be great to have 5.8 compatibility on "LaravelMondialRelay" :)

**Comment by QuentinBontemps** [comment]
Done ;)

**Pull request merged**
